# Generated by Django 4.2.4 on 2023-10-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char', '0002_runenifelheimtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runenifelheimtoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
