# Generated by Django 4.2.4 on 2023-10-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccRegNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('key', models.CharField(max_length=32)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
