# Generated by Django 4.2.4 on 2023-10-21 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0004_auto_20201013_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='added',
            field=models.DateTimeField(auto_now_add=True, help_text='Data em que foi criado no RagCP'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='Conta que criou esta entrada. Caso venha de outra rede social, usará qualquer conta do sistema', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, help_text='o corpo da postagem', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(default=None, help_text='Chave estrangeira para outro post caso seja uma resposta', null=True, on_delete=django.db.models.deletion.CASCADE, to='content.post', verbose_name='Em resposta a'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reference',
            field=models.CharField(default=None, help_text='Link para a postagem original caso venha de outra rede social', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='O título da postagem', max_length=256),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Data em que foi modificado'),
        ),
    ]
